/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, PaymentVoucher as PrismaPaymentVoucher } from "@prisma/client";

export class PaymentVoucherServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.PaymentVoucherCountArgs, "select">
  ): Promise<number> {
    return this.prisma.paymentVoucher.count(args);
  }

  async paymentVouchers<T extends Prisma.PaymentVoucherFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.PaymentVoucherFindManyArgs>
  ): Promise<PrismaPaymentVoucher[]> {
    return this.prisma.paymentVoucher.findMany<Prisma.PaymentVoucherFindManyArgs>(
      args
    );
  }
  async paymentVoucher<T extends Prisma.PaymentVoucherFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.PaymentVoucherFindUniqueArgs>
  ): Promise<PrismaPaymentVoucher | null> {
    return this.prisma.paymentVoucher.findUnique(args);
  }
  async createPaymentVoucher<T extends Prisma.PaymentVoucherCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.PaymentVoucherCreateArgs>
  ): Promise<PrismaPaymentVoucher> {
    return this.prisma.paymentVoucher.create<T>(args);
  }
  async updatePaymentVoucher<T extends Prisma.PaymentVoucherUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.PaymentVoucherUpdateArgs>
  ): Promise<PrismaPaymentVoucher> {
    return this.prisma.paymentVoucher.update<T>(args);
  }
  async deletePaymentVoucher<T extends Prisma.PaymentVoucherDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.PaymentVoucherDeleteArgs>
  ): Promise<PrismaPaymentVoucher> {
    return this.prisma.paymentVoucher.delete(args);
  }
}
