/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Ledger as PrismaLedger } from "@prisma/client";

export class LedgerServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.LedgerCountArgs, "select">): Promise<number> {
    return this.prisma.ledger.count(args);
  }

  async ledgers<T extends Prisma.LedgerFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.LedgerFindManyArgs>
  ): Promise<PrismaLedger[]> {
    return this.prisma.ledger.findMany<Prisma.LedgerFindManyArgs>(args);
  }
  async ledger<T extends Prisma.LedgerFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.LedgerFindUniqueArgs>
  ): Promise<PrismaLedger | null> {
    return this.prisma.ledger.findUnique(args);
  }
  async createLedger<T extends Prisma.LedgerCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.LedgerCreateArgs>
  ): Promise<PrismaLedger> {
    return this.prisma.ledger.create<T>(args);
  }
  async updateLedger<T extends Prisma.LedgerUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.LedgerUpdateArgs>
  ): Promise<PrismaLedger> {
    return this.prisma.ledger.update<T>(args);
  }
  async deleteLedger<T extends Prisma.LedgerDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.LedgerDeleteArgs>
  ): Promise<PrismaLedger> {
    return this.prisma.ledger.delete(args);
  }
}
