/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Site } from "./Site";
import { SiteCountArgs } from "./SiteCountArgs";
import { SiteFindManyArgs } from "./SiteFindManyArgs";
import { SiteFindUniqueArgs } from "./SiteFindUniqueArgs";
import { DeleteSiteArgs } from "./DeleteSiteArgs";
import { SiteService } from "../site.service";
@graphql.Resolver(() => Site)
export class SiteResolverBase {
  constructor(protected readonly service: SiteService) {}

  async _sitesMeta(
    @graphql.Args() args: SiteCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Site])
  async sites(@graphql.Args() args: SiteFindManyArgs): Promise<Site[]> {
    return this.service.sites(args);
  }

  @graphql.Query(() => Site, { nullable: true })
  async site(@graphql.Args() args: SiteFindUniqueArgs): Promise<Site | null> {
    const result = await this.service.site(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Site)
  async deleteSite(@graphql.Args() args: DeleteSiteArgs): Promise<Site | null> {
    try {
      return await this.service.deleteSite(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
